name: tests

on:
    push:
        branches:
            - main
            - '*.x'
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    phpunit:
        name: PHP ${{ matrix.php }} / ${{ matrix.deps }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: ['8.1', '8.2', '8.3']
                deps: [highest]
                include:
                    - php: '8.1'
                      deps: lowest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  ini-values: error_reporting=E_ALL
                  tools: composer:v2
                  coverage: xdebug

            - name: Install Composer dependencies
              uses: ramsey/composer-install@v2
              with:
                  dependency-versions: ${{ matrix.deps }}

            - name: Run PHPUnit
              run: vendor/bin/phpunit
